#! /usr/bin/env python
from string import Template
from os.path import expanduser
import sys
import os

def main():
    """ Create the template file """
    filein = open('wallpaperstart.template')
    template = Template(filein.read())
    scriptDir = os.path.dirname(os.path.abspath(sys.argv[0]))
    d = {"scriptPath" : os.path.join(scriptDir, "wallpaper.sh"),
         "arg" : os.path.join(scriptDir, "wallpaper_conf.txt")}
    autostartPart = template.substitute(d)

    """ write the generated template to autostart """
    autostartDirStr = os.path.expanduser("~/.config/autostart")
    if not os.path.exists(autostartDirStr):
        os.makedirs(autostartDirStr)
    autostartFileStr = os.path.join(autostartDirStr, "wallpaperCycler.desktop")
    if not os.path.isfile(autostartFileStr):        
        with open(autostartFileStr, "wr+") as autostartFile:
            autostartFile.write(autostartPart)

if __name__ == "__main__":
    main()
